package org.netra.features.karma.entity;

public enum KarmaEventType {
    VERIFIED_DONATION_COMPLETED,
    BLOOD_REQUEST_FULFILLED,
    DONOR_COMMITMENT_COMPLETED,
    EVENT_PARTICIPATION_COMPLETED,
    FAKE_REQUEST_CONFIRMED,
    DONOR_NO_SHOW_CONFIRMED,
    ADMIN_ADJUSTMENT,
    COMPENSATING_REVERSAL
}
