package org.netra.features.notification.entity;

public enum NotificationType {
    MATCH_CREATED,
    MATCH_ACCEPTED,
    MATCH_DECLINED,
    MATCH_EXPIRED,
    BLOOD_REQUEST_CANCELLED,
    EMERGENCY_REQUEST_CREATED,
    DONATION_SUBMITTED,
    DONATION_VERIFIED,
    DONATION_REJECTED,
    FULFILLMENT_CREATED,
    FULFILLMENT_STARTED,
    FULFILLMENT_COMPLETED,
    FULFILLMENT_FAILED,
    FULFILLMENT_CANCELLED
}
